import { Component, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';

import { USER_GUIDE_STEPS, WalkthroughStep } from '../walkthrough-dialog/user-guide-data';

@Component({
  selector: 'app-user-guide-print',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatDividerModule],
  template: `
    <div class="print-container">
      <div class="no-print header-actions">
        <button mat-raised-button color="primary" (click)="print()">
          <mat-icon>print</mat-icon>
          Print / Save as PDF
        </button>
      </div>

      <header class="guide-header">
        <h1>Global Gadgets User Guide</h1>
        <p>A step-by-step walkthrough of the Global Gadgets application.</p>
      </header>

      <div class="steps-list">
        @for (step of steps; track step; let last = $last) {
          <div class="step-item">
            <div class="step-icon">
              <mat-icon>{{step.icon}}</mat-icon>
            </div>
            <div class="step-content">
              <h2>{{step.title}}</h2>
              <div [innerHTML]="step.description"></div>
            </div>
          </div>
          @if (!last) {
            <mat-divider></mat-divider>
          }
        }
      </div>
     
      <footer class="guide-footer">
        <p>Generated by Global Gadgets Application</p>
      </footer>
    </div>
  `,
  styles: [`
    .print-container {
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      font-family: 'Google Sans', 'Roboto', sans-serif;
      color: #333;
    }

    h1, h2, h3 {
      font-weight: 500;
    }

    .header-actions {
      margin-bottom: 20px;
      text-align: right;
    }

    .guide-header {
      text-align: center;
      margin-bottom: 40px;
      
      h1 {
        font-size: 32px;
        color: #1976d2;
        margin-bottom: 8px;
      }
      
      p {
        font-size: 18px;
        color: #666;
      }
    }

    .step-item {
      display: flex;
      gap: 24px;
      padding: 32px 0;
      
      .step-icon {
        flex-shrink: 0;
        
        mat-icon {
          font-size: 48px;
          width: 48px;
          height: 48px;
          color: #1976d2;
        }
      }
      
      .step-content {
        h2 {
          margin-top: 0;
          font-size: 22px;
          margin-bottom: 12px;
        }
        
        div {
          font-size: 16px;
          line-height: 1.6;
          color: #555;
        }
      }
    }

    .guide-footer {
      margin-top: 40px;
      text-align: center;
      font-size: 12px;
      color: #999;
      border-top: 1px solid #eee;
      padding-top: 20px;
    }

    @media print {
      .no-print {
        display: none !important;
      }
      .print-container {
        padding: 0;
        max-width: 100%;
      }
    }
  `]
})
export class UserGuidePrintComponent {
  steps: WalkthroughStep[] = USER_GUIDE_STEPS;

  print() {
    window.print();
  }
}
